"""empty message

Revision ID: a47b14dd3837
Revises: e40e06840abb
Create Date: 2025-05-14 00:56:42.282405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47b14dd3837'
down_revision = 'e40e06840abb'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_corte_caja")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corte_caja', schema=None) as batch_op:
        # añadimos usuario_id con default '1' para poblar filas existentes
        batch_op.add_column(
            sa.Column('usuario_id', sa.Integer(),
                      nullable=False,
                      server_default='1')
        )
        # nombre explícito para la FK
        batch_op.create_foreign_key(
            'fk_corte_caja_usuario_id_usuario',
            'usuario',
            ['usuario_id'],
            ['id']
        )
    # opcional: si quieres que futuras inserciones no tengan default,
    # descomenta este bloque:
    # with op.batch_alter_table('corte_caja', schema=None) as batch_op:
    #     batch_op.alter_column('usuario_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corte_caja', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_corte_caja_usuario_id_usuario',
            type_='foreignkey'
        )
        batch_op.drop_column('usuario_id')
    # ### end Alembic commands ###