"""Agrega columna entregado a OrdenDetalle

Revision ID: e40e06840abb
Revises: 
Create Date: 2025-04-24 20:54:05.127197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40e06840abb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_detalle', schema=None) as batch_op:
        batch_op.drop_column('entregado')

    # ### end Alembic commands ###
